### ISSUE TITLE
Add ability to ignore a specific update

### ISSUE THREAD

**Issue by Ampa** [swar8080/obsidian-plugin-update-tracker#11]
Hello, and thanks for the great plugin.

Was wondering whether you could add the ability to ignore a specific update for a given plugin.

For example: I am being informed that v2.0.0 Beta 2 is available for the Calendar plugin, but have chosen not to install this beta due to some known issues. So I want to tell Plugin Update Tracker to ignore the Calendar update until there is a new release such as v2.0.0 Beta 3.

Thanks,
Ampa.

**Comment by swar8080** [comment]
Hey thanks for the suggestion, that's something I plan to add

**Comment by swar8080** [comment]
Added this in v1.1.0

**Comment by Ampa** [comment]
Thanks for adding my suggestion!

**Comment by Ampa** [comment]
Something seems a little buggy with this function.

Usually when I ignore an update it continues to appear in the list until I ignore it a second time.

This happened with both Calendar and Periodic Notes.

**Comment by swar8080** [comment]
@Ampa i'm guessing the user interface is confusing/misleading, but let me know otherwise:

When there are 3 new uninstalled versions then the "Ignore Versions" button needs to be pressed three times. The idea was that if version 1.0.0 is installed then someone might want to ignore v1.0.2 but install v1.0.1. From the plugin settings you could unhide plugin versions to verify this if you want

If that's the case i'll think of how to make the UI clearer - and let me know if you have any ideas

**Comment by Ampa** [comment]
Ah OK, that is almost certainly what is happening.

I certainly never guessed that was the functionality!
