### ISSUE TITLE
Installs but fails to load under iPadOS

### ISSUE THREAD

**Issue by johnthebeard** [swar8080/obsidian-plugin-update-tracker#5]
When I try to activate the plugin I get a "Failed to load plugin" error. (I've been through multiple cycles of uninstalling/reinstalling/restarting with the same behaviour recurring.) Using Obsidian version 1.4.1 (83), API v1.0.3 on an iPad Mini 4 under iPadOS 15.6.1.

**Comment by swar8080** [comment]
Thanks for the heads up, I'll debug it when I get my hands on an ipad

**Comment by Calorion** [comment]
Yes, this will not enable for me on iPadOS 15.7.1 either.

**Comment by swar8080** [comment]
@Calorion thanks for the error details

The issue was I was using a javascript feature that isn't supported by capacitorjs, which i've fixed

Unfortunately there's no status bar on mobile devices so you can't actually view the update list on ipad. I'll create a new issue for adding that as a feature, likely displaying the icon on the sidebar instead.

**Comment by Calorion** [comment]
There are now three plugins I've run into recently with this issue. Has capacitor.js changed recently? Perhaps a bug report to them is in order.
