### ISSUE TITLE
Error when no internet connection 

### ISSUE THREAD

**Issue by 1C0D** [swar8080/obsidian-plugin-update-tracker#68]
It's sending an error in the console. a console log could be enough
obsidian-plugin-update-tracker:800 Error fetching releases Error: net::ERR_INTERNET_DISCONNECTED
    at Si

**Comment by 1C0D** [comment]
Another thing there is a timer to tell when checking for updates again. But when restarting, it's not re-initialized. Maybe an option to force re-initialize on restart. Just for when doing own plugins to see the result after releasing it...

**Comment by 1C0D** [comment]
Now I can see the update I couldn't see a few hours ago. But there is a problem, I'm under the vault where I developed the plugin, so it shouldn't appear in updates. I mean, it was not installed through the obsidian plugin installer. And of course if I go in the obsidian plugin update it won't find it. So I guess there is a way to check if it was installed just checking the folder is only containing js file and not ts files?

**Comment by swar8080** [comment]
Hello

>It's sending an error in the console. a console log could be enough
obsidian-plugin-update-tracker:800 Error fetching releases Error: net::ERR_INTERNET_DISCONNECTED

https://jc5gpa3gs7o2uge6iq5mgjd53q0daomi.lambda-url.us-east-1.on.aws is this plugin's backend URL if you want to debug why you're unable to connect

An error in the console seems OK since it helps people debug

> Now I can see the update I couldn't see a few hours **ago**...
Another thing there is a timer to tell when checking for updates again. But when restarting, it's not re-initialized. Maybe an option to force re-initialize on restart.

It does re-check for updates when restarting obsidian, but sometimes that check is very fast so you don't see the ⌛

The backend caches plugins' most recent version to avoid making API calls to github for every plugin. It'll use cached version info from up to `Math.ceil(number of requested plugins / 50) * 30` seconds ago. That explains the delay seeing your plugin's update

So likely on your first time loading obsidian you have a less-common plugin with an old cached value, so it makes a slow request to github. Then when restarting obsidian, all plugin versions come from the cache, so the response time is very fast

> I'm under the vault where I developed the plugin, so it shouldn't appear in updates. I mean, it was not installed through the obsidian plugin installer. And of course if I go in the obsidian plugin update it won't find it. So I guess there is a way to check if it was installed just checking the folder is only containing js file and not ts files?

This plugin's backend compares the version you have installed locally to the versions in your [github releases](https://github.com/1C0D/duplicate-line-obsidian/releases). If the version in your releases is greater than the manifest's version on your `main` branch then it'll be showed as a "Beta" version like:

![image](https://github.com/swar8080/obsidian-plugin-update-tracker/assets/17691679/da9acaf6-d906-4bad-9e70-941ef9b0c083)

**Comment by 1C0D** [comment]
A simple warning would be better, or a debug mode.
I have this error because often when I start my computer, I switch on my internet too. and it's longer that restart and e.g: start obsidian. So I have no connexion at this moment. I guess. After there are often some little cuts on the internet due to my provider in France... 
I think you didn't understand the part where I'm explaining if a plugin has been installed through obsidian or cloned from github and built... it should propose an update in this case. Because if I update my own plugin, and I'm on the vault I use to do plugins, it's not a good idea to update this plugin... or maybe I miss something in the process that I didn't test entirely (doing the update).

**Comment by swar8080** [comment]
>  So I guess there is a way to check if it was installed just checking the folder is only containing js file and not ts files?

There isn't because obsidian can only read js files and not ts files. main.ts shows up in developer tools because of source maps but if you check the .obsidian/plugins/<plugin-name> directory you'll see a main.js file

> Because if I update my own plugin, and I'm on the vault I use to do plugins, it's not a good idea to update this plugin...
This plugin shouldn't suggest an update as long as your plugin's manifest `version` installed locally is `>=` its manifest version on your latest github releases

**Comment by 1C0D** [comment]
So I guess there is a way to check if it was installed just checking the folder is only containing js file and not ts files?  
it was a suggestion to know it a plugin was installed or cloned  
if installed:  
- main.js & manifest in the folder
if cloned or developed:  
- main.js (maybe) manifest (sure) ts files in directory/subdirectory
I don't know how obsidian deals with this exactly, but it can do the difference 
e.g: after an update on a plugin you are developing (and published of course):    
- on the vault where the plugin is developped, updating plugins, no upadate available   
- on a vault where the plugin is installed, updating plugins, an update is available  
   
your plugin proposes an update in both situations

**Comment by swar8080** [comment]
> on the vault where the plugin is developped, updating plugins...your plugin proposes an update

This is intentional, as long as this logic is working correctly:
>This plugin shouldn't suggest an update as long as your plugin's manifest version installed locally is >= its manifest version on your latest github releases

If it's not, then it might be an unintentional bug

But either way this would only be a problem for people that develop plugins in the same vault they use, so I likely won't change this plugin at all. Personally I have a separate vault for plugin development, which you could create without this plugin installed if the update suggestions are causing problems

**Comment by 1C0D** [comment]
So if you update anyway, it's not deleting the whole directory? 
because personally I have a vault for plugin development too, but inside I also use some plugin that I can decide to edit, and then I don't remember if it was installed or in development. I check this, opening the folder generally.
But anyway, it's a small issue indeed.

**Comment by swar8080** [comment]
I see, so this plugin will replace the `main.js`, `style.css`, and `manifest.json` during update, which could overwrite some of your changes
